struct AnimationGlobals {
    instance_count:      u32,
    bone_count:          u32,
    bounding_radius:     f32,
    channel_data_offset: u32,
    keyframe_data_offset: u32,
    screen_width:        u32,
    screen_height:       u32,
    hiz_mip_count:       u32,
    planes:              array<FrustumPlane, 6>,
    proj_x:              f32,
    culling_enabled:     u32,
    _pad4:               vec2<f32>,
    view_proj:           mat4x4<f32>,
    bounding_min:        vec3<f32>,
    _pad5:               f32,
    bounding_max:        vec3<f32>,
    _pad6:               f32,
}
