struct GlobalData {
    instance_count:  u32,
    delta_time:      f32,
    bounding_radius: f32,
    screen_width:    u32,
    screen_height:   u32,
    hiz_mip_count:   u32,
    proj_x:          f32,
    _pad0:           f32,
    planes:          array<FrustumPlane, 6>,
    view_proj:       mat4x4<f32>,
    bounding_min:    vec3<f32>,
    _pad1:           f32,
    bounding_max:    vec3<f32>,
    _pad2:           f32,
}
