dir: '{{.InterfaceDir}}/mocks'
structname: Mock{{.InterfaceName}}
filename: "mock_{{.InterfaceName | snakecase}}.go"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/Carmen-Shannon/oxy-go/common:
    config:
      exclude-interface-regex: Option$
      include-interface-regex: ^[A-Z]
      recursive: true
  github.com/Carmen-Shannon/oxy-go/engine:
    config:
      exclude-interface-regex: Option$
      include-interface-regex: ^[A-Z]
      recursive: true
