with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
outpkg: "mocks"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/Carmen-Shannon/oxy-go/common:
    config:
      recursive: true
      include-regex: "^[A-Z]"
      exclude-regex: "Option$"
  github.com/Carmen-Shannon/oxy-go/engine:
    config:
      recursive: true
      include-regex: "^[A-Z]"
      exclude-regex: "Option$"
