package common

// Virtual key codes for cross-platform input handling.
// These values match GLFW key codes which use ASCII values for printable keys.
// Reference: https://pkg.go.dev/github.com/go-gl/glfw/v3.4/glfw#Key
const (
	KeyW         = 87  // W key (ASCII)
	KeyA         = 65  // A key (ASCII)
	KeyS         = 83  // S key (ASCII)
	KeyD         = 68  // D key (ASCII)
	KeyQ         = 81  // Q key (ASCII)
	KeyE         = 69  // E key (ASCII)
	KeyB         = 66  // B key (ASCII)
	KeyC         = 67  // C key (ASCII)
	KeyF         = 70  // F key (ASCII)
	KeyG         = 71  // G key (ASCII)
	KeyH         = 72  // H key (ASCII)
	KeyI         = 73  // I key (ASCII)
	KeyJ         = 74  // J key (ASCII)
	KeyK         = 75  // K key (ASCII)
	KeyL         = 76  // L key (ASCII)
	KeyM         = 77  // M key (ASCII)
	KeyN         = 78  // N key (ASCII)
	KeyO         = 79  // O key (ASCII)
	KeyP         = 80  // P key (ASCII)
	KeyR         = 82  // R key (ASCII)
	KeyT         = 84  // T key (ASCII)
	KeyU         = 85  // U key (ASCII)
	KeyV         = 86  // V key (ASCII)
	KeyX         = 88  // X key (ASCII)
	KeyY         = 89  // Y key (ASCII)
	KeyZ         = 90  // Z key (ASCII)
	KeySpace     = 32  // Spacebar (ASCII)
	KeyBackspace = 259 // Backspace key (GLFW)
	KeyEsc       = 256 // Escape key (GLFW)

	Key0 = 48 // 0 key (ASCII)
	Key1 = 49 // 1 key (ASCII)
	Key2 = 50 // 2 key (ASCII)
	Key3 = 51 // 3 key (ASCII)
	Key4 = 52 // 4 key (ASCII)
	Key5 = 53 // 5 key (ASCII)
	Key6 = 54 // 6 key (ASCII)
	Key7 = 55 // 7 key (ASCII)
	Key8 = 56 // 8 key (ASCII)
	Key9 = 57 // 9 key (ASCII)
)

// Additional non-printable keys
const (
	KeyTab        = 258 // Tab key (GLFW)
	KeyRight      = 262 // Right Arrow (GLFW)
	KeyLeft       = 263 // Left Arrow (GLFW)
	KeyDown       = 264 // Down Arrow (GLFW)
	KeyUp         = 265 // Up Arrow (GLFW)
	KeyLeftShift  = 340 // Left Shift (GLFW)
	KeyLeftCtrl   = 341 // Left Ctrl (GLFW)
	KeyLeftAlt    = 342 // Left Alt (GLFW)
	KeyRightShift = 344 // Right Shift (GLFW)
	KeyRightCtrl  = 345 // Right Ctrl (GLFW)
	KeyRightAlt   = 346 // Right Alt (GLFW)
	KeyF1         = 290 // F1 key (GLFW)
	KeyF2         = 291 // F2 key (GLFW)
	KeyF3         = 292 // F3 key (GLFW)
	KeyF4         = 293 // F4 key (GLFW)
	KeyF5         = 294 // F5 key (GLFW)
	KeyF6         = 295 // F6 key (GLFW)
	KeyF7         = 296 // F7 key (GLFW)
	KeyF8         = 297 // F8 key (GLFW)
	KeyF9         = 298 // F9 key (GLFW)
	KeyF10        = 299 // F10 key (GLFW)
	KeyF11        = 300 // F11 key (GLFW)
	KeyF12        = 301 // F12 key (GLFW)
)
